FROM node:22-alpine

# Basic packages
RUN apk add --no-cache \
  bash \
  curl \
  openjdk21-jre

# Install Bun
RUN curl -fsSL https://bun.sh/install | bash
ENV BUN_INSTALL=/root/.bun
ENV PATH=$BUN_INSTALL/bin:$PATH
RUN [ -e /root/.bun/bin/bunx ] || ln -s /root/.bun/bin/bun /root/.bun/bin/bunx

# Install Firebase CLI
RUN bun install -g firebase-tools

# Copy firebase directory to workspace
COPY container-data/firebase firebase

# Install dependencies
RUN cd firebase/functions && bun install

# Run emulators
RUN cd firebase && firebase emulators:exec "echo 'Firebase emulators are ready'" --project demo-env-spawner

WORKDIR /workspace

CMD ["sh"]
