FROM node:22-alpine

# Basic packages
RUN apk add --no-cache \
    bash \
    curl

# Install Bun
RUN curl -fsSL https://bun.sh/install | bash
ENV BUN_INSTALL=/root/.bun
ENV PATH=$BUN_INSTALL/bin:$PATH
RUN [ -e /root/.bun/bin/bunx ] || ln -s /root/.bun/bin/bun /root/.bun/bin/bunx

# Install Ionic CLI
RUN bun install -g @ionic/cli

WORKDIR /workspace

CMD ["sh"]
